<a href="https://colab.research.google.com/github/YMGYM/python_deeplearning_pytorch/blob/main/Pytorch_part1~.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

이 노트북은 `파이썬 딥러닝 파이토치` 책의 연습코드입니다.

코드는 [이곳](https://github.com/Justin-A/DeepLearning101) 에서 전문을 확인 가능합니다.

이 노트북은 1장~ 내용을 다루고 있습니다.

# 파이토치 기초

## 환경 구축 및 토치 설치

Google Colab을 통해 진행하기 때문에 이 부분은 생략하겠다.

Colab에는 Torch가 이미 설치되어 있다.

In [2]:
import torch

torch.__version__ # 토치의 버전을 확인하는 코드

'1.7.0+cu101'

## 1 - 4 반드시 알아야 하는 파이토치 스킬

### 1) 텐서

#### Scalar
상수값. (차원이 없는 값)

파이썬의 기본연산자와 `torch` 메소드를 통해 사용이 가능하다.

In [3]:
import torch
scalar1 = torch.tensor([1.])
scalar2 = torch.tensor([3.])

print(scalar1)
print(scalar2)

tensor([1.])
tensor([3.])


In [4]:
# 사칙연산자
add_scalar = scalar1 + scalar2
print(add_scalar)

sub_scalar = scalar1 - scalar2
print(sub_scalar)

mul_scalar = scalar1 * scalar2
print(mul_scalar)

div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])


In [5]:
# torch 모듈의 메소드로 연산 위와 결과가 같다.
print(torch.add(scalar1, scalar2))
print(torch.sub(scalar1, scalar2))
print(torch.mul(scalar1, scalar2))
print(torch.div(scalar1, scalar2))

tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])


#### Vector

값을 2개 이상의 수치로 표현하는 방법

스칼라 사칙연산과 동일한 방법으로 연산이 가능하나, 사칙연산의 경우 element-wise 하게 계산됨

In [6]:
 # 벡터 정의
 vector1 = torch.tensor([1., 2., 3.])
 vector2 = torch.tensor([4., 5., 6.])

 print(vector1)
 print(vector2)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [7]:
# 벡터와 사칙연산자
add_vector = vector1 + vector2
print(add_vector)

sub_vector = vector1 - vector2
print(sub_vector)

mul_vector = vector1 * vector2 # element-wise 하게 계산
print(mul_vector)

div_vector = vector1 / vector2 # element-wise 하게 계산
print(div_vector)

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])


In [8]:
# 내장 메소드를 사용한 연산
print(torch.add(vector1, vector2))
print(torch.sub(vector1, vector2))
print(torch.mul(vector1, vector2)) # element-wise 하게 계산
print(torch.div(vector1, vector2)) # element-wise 하게 계산

# 벡터 간 내적은 다음과 같이 계산
print(torch.dot(vector1, vector2)) 

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])
tensor(32.)


#### Matrix

행렬은 2개 이상의 벡터값을 통합해 구성된 값이다.

사칙 연산 또한 연산자와 내장 메소드로 구현이 가능하며, element-wise하게 계산된다.

In [9]:
# 행렬 선언
matrix1 = torch.tensor([[1.,2.],[3.,4.]])
matrix2 = torch.tensor([[5.,6.],[7.,8.]])

print(matrix1)
print(matrix2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [11]:
# 행렬 간 사칙연산
add_matrix = matrix1 + matrix2
print(add_matrix)

sub_matrix = matrix1 - matrix2
print(sub_matrix)

mul_matrix = matrix1 * matrix2 # element-wise
print(mul_matrix)

div_matrix = matrix1 / matrix2 # element-wise
print(div_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [12]:
# 내장 메소드를 사용한 연산과정
print(torch.add(matrix1, matrix2))
print(torch.sub(matrix1, matrix2))
print(torch.mul(matrix1, matrix2)) # element-wise
print(torch.div(matrix1, matrix2)) # element-wise

# 행렬의 곱연산 실행
print(torch.matmul(matrix1, matrix2))

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [13]:
# TF에서는 Dot연산자를 사용해서도 되던데 토치도 가능할까?
torch.dot(matrix1, matrix2)

RuntimeError: ignored

안된다..ㅋㅋㅋ

Torch에서는 2차원 이상의 데이터는 `torch.matmul`을 사용할 필요가 있어 보인다

#### Tensor

텐서는 2차원 이상의 배열이라 표현.

마찬가지로 사칙연산자와 내장 메소드를 사용해 계산이 가능하며, element-wise 하게 계산된다.

In [15]:
tensor1 = torch.tensor([[[1.,2.],[3.,4.]], [[5.,6.],[7.,8.]]])
print(tensor1)

print(tensor1.shape) # numpy의 shape메소드를 확인하는 게 아니다..

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([2, 2, 2])


In [16]:
tensor2 = torch.tensor([[[9.,10.],[11.,12.]],[[13.,14.], [15.,16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [17]:
# 사칙연산자를 사용한 연산
add_tensor = tensor1 + tensor2
print(add_tensor)

sub_tensor = tensor1 - tensor2
print(sub_tensor)

mul_tensor = tensor1 * tensor2 # element-wise 하게 계산됨
print(mul_tensor)

div_tensor = tensor1 / tensor2 # element-wise 하게 계산됨
print(div_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])
tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [18]:
# 내장 연산자를 사용해 계산
print(torch.add(tensor1, tensor2))
print(torch.sub(tensor1, tensor2))
print(torch.mul(tensor1, tensor2)) # element-wise
print(torch.div(tensor1, tensor2)) # element-wise

# 내적합
multed_tensor = torch.matmul(tensor1, tensor2)
print(multed_tensor)

print(multed_tensor.shape) # shape 확인

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])
tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])
tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])
torch.Size([2, 2, 2])


3차원 텐서의 계산 과정은 다음과 같다
```plain
[
  [
    [1*9  + 2*11] [1*10 + 2*12]
    [5*13 + 6*15] [5*14 + 6*16]
                                ]
  [
    [3*9  + 4*11] [3*10 + 4*12]
    [7*13 + 8*15] [7*14 + 8*16]
                                ]
                                  ]
```

앞 차원을 그대로 두고 하위 2개의 차원의 matmul이다.

#### AutoGrad

In [2]:
# Devise 설정
import torch

if torch.cuda.is_available():
  print("use cuda")
  DEVICE = torch.device('cuda')
else:
  print("use cpu")
  DEVICE = torch.device('cpu')

use cpu


In [4]:
# hyperparameter 설정
BATCH_SIZE = 64
INPUT_SIZE = 1000 
HIDDEN_SIZE = 100 # (1000, 100) 짜리 히든 레이어와 (100,10) 짜리 히든레이어 생성을 위함
OUTPUT_SIZE = 10

In [10]:
# 레이어 생성
x = torch.randn(BATCH_SIZE, INPUT_SIZE, device=DEVICE, dtype=torch.float, requires_grad=False) # 단순한 input이므로 gradient 가 필요 없다.
y = torch.randn(BATCH_SIZE, OUTPUT_SIZE, device=DEVICE, dtype=torch.float, requires_grad=False) # 단순한 output이므로 gradient 가 필요 없다.

w1 = torch.randn(INPUT_SIZE, HIDDEN_SIZE, device=DEVICE, dtype=torch.float, requires_grad=True) # 가중치 갱신을 위해
w2 = torch.randn(HIDDEN_SIZE, OUTPUT_SIZE, device=DEVICE, dtype=torch.float, requires_grad=True)

In [18]:
# 학습?
learning_rate = 1e-6
for t in range(1, 501):
  y_pred = x.mm(w1).clamp(min = 0).mm(w2) # 순전파 계산. clamp는 reLU와 같은 역할을 하는듯 (비선형 활성화 함수)

  loss = (y_pred - y).pow(2).sum() # MSE 오차.

  if t % 100 == 0:
    print("Iteration: ", t, "\t", "Loss: ", loss.item()) # 100번 반복 시 loss값 모니터링
  loss.backward() # 각 파라미터 값에 대해 Gradient를 구하고 역전파를 진행할 수 있게 결과를 반환.

  with torch.no_grad(): # 해당 블록을 history tracking 하지 않겠다는 뜻이다.
    w1 -= learning_rate * w1.grad # optimization진행
    w2 -= learning_rate * w2.grad

    w1.grad.zero_() # Gradient값을 다시 0으로 설정해 둠.
    w2.grad.zero_()

Iteration:  100 	 Loss:  0.000153534158016555
Iteration:  200 	 Loss:  5.0981157983187586e-05
Iteration:  300 	 Loss:  2.521771784813609e-05
Iteration:  400 	 Loss:  1.6163408872671425e-05
Iteration:  500 	 Loss:  1.1777397958212532e-05


In [ ]:
y - y_pred # 상당히 작은 수들이 출력되는 것을 확인할 수 있다.

In [15]:
w1.grad # gradient를 호출하는 메소드이다...

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [17]:
y.grad # gradient를 설정하지 않으면 None값이 반환되는 듯 하다.